### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by alexandrarautu** [alexandruradovici/alf-alfy-language-public#5]
When I try to run the do_function_with_expression file. It gives me this error:

SyntaxError: Unexpected token a in JSON at position 8
    at Object.parse (native)
    at Object.anonymous (/Users/alexandra.rautu/Desktop/alfy.js:356:37)
    at Object.parse (/Users/alexandra.rautu/Desktop/alfy.js:1302:36)
    at Object.<anonymous> (/Users/alexandra.rautu/Desktop/main.js:12:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

I don't understand from where it comes and how to treat it. Any hints? I looke at alfy.js:356:37 , alfy.js:1302:36 and at main.js:12:23 , but there isn't something weird.

**Comment by alexandruradovici** [comment]
Do you use JSON.parse anywhere?

On Apr 20, 2017 13:51, "Alexandra Rautu" <notifications@github.com> wrote:

When I try to run the do_function_with_expression file. It gives me this
error:

SyntaxError: Unexpected token a in JSON at position 8
at Object.parse (native)
at Object.anonymous (/Users/alexandra.rautu/Desktop/alfy.js:356:37)
at Object.parse (/Users/alexandra.rautu/Desktop/alfy.js:1302:36)
at Object. (/Users/alexandra.rautu/Desktop/main.js:12:23)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)

I don't understand from where it comes and how to treat it. Any hints? I
looke at alfy.js:356:37 , alfy.js:1302:36 and at main.js:12:23 , but there
isn't something weird.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexandruradovici/alf-alfy-language-public/issues/5>,
or mute the thread

**Comment by alexandrarautu** [comment]
No, I don't use it

**Comment by alexandruradovici** [comment]
send me a private email with the code please.
